name: pouch

services:
  app:
    depends_on:
      database:
        condition: service_healthy
    container_name: pouch_app
    build: ./app
    restart: unless-stopped
    volumes:
      - ../:/opt/app
    environment:
      NODE_ENV: ${NODE_ENV}
  nginx:
    depends_on:
      - app
    container_name: pouch_nginx
    image: nginx:1.23
    ports:
      - "3000:80"
    restart: unless-stopped
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/storage/logs:/var/logs/nginx
  database:
    container_name: pouch_database
    image: mariadb:10.6
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/storage/lib:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "mariadb --user=${DB_USERNAME} --password=${DB_PASSWORD} ${DB_DATABASE}"]
      interval: 1s
      timeout: 5s
      retries: 120
      start_period: 10s
  redis:
    container_name: pouch_redis
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
